---
name: ci

on:
  push:
    branches: [ main ]
    paths-ignore: [ "README.md", "LICENSE"]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "README.md", "LICENSE"]

jobs:
  ci:
    name: Build dotfiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - name: "install nix ❄️"
      uses: cachix/install-nix-action@v18

    - name: "check formatting"
      run: "git ls-files '*.nix' | xargs nix develop -c nixpkgs-fmt --check"
