---
name: ci

on:
  push:
    branches: [ main ]
    paths-ignore: [ "README.md", "LICENSE"]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "README.md", "LICENSE"]

jobs:
  format:
    name: check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: "install nix ❄️"
      uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7 # v24

    - name: "check formatting"
      run: "nix develop -c nixpkgs-fmt --check ."
