---
name: ci

on:
  push:
    branches: [ main ]
    paths-ignore: [ "README.md", "LICENSE"]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "README.md", "LICENSE"]

jobs:
  format:
    name: check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0

    - name: "install nix ❄️"
      uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23

    - name: "check formatting"
      run: "nix develop -c nixpkgs-fmt --check ."
