---
name: update nix-vscode-extensions input

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 4 * * *' # runs daily at 04:00 UTC

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.5.3

      - name: install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          inputs: "nix-vscode-extensions"
          token: ${{ secrets.NIX_FLAKES_UPDATE_TOKEN }}
          pr-title: "chore(vscode): update nix-vscode-extensions input"
          commit-msg: "chore(vscode): update nix-vscode-extensions input"
          branch: "update_nix_vscode_extensions"
          git-author-name: "JesusMtnez[bot]"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-name: "JesusMtnez[bot]"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"

      - name: set automerge for the pr
        if: ${{ steps.update.outputs.pull-request-operation }} == 'created'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ steps.update.outputs.pull-request-number }}
        run: gh pr merge --auto --squash --delete-branch $PR
